### ISSUE TITLE
Have you considered adding non cached buildpack packages?

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/buildpack-releases#1]
You wouldn't have to add them into cf-release but having them in this release those of us who wish to use non cached buildpacks can.

**Comment by flavorjones** [comment]
@Dannyzen Any thoughts here?

**Comment by Dannyzen** [comment]
@youngm What would be your use case for having non-cached buildpack packages included and why would it be helpful for you?

**Comment by youngm** [comment]
@Dannyzen  We always use the non cached buildpacks so our users can continue using older versions of packages when necessary after they've been upgraded and removed from the cached buildpacks.  We don't have things like proxies getting in the way during staging.

It would be nice if we could manage the installation and such of our non cached bulidpacks the same way the cached buildpacks work.  Are non cached buildpacks bad or not useful in some way I'm not aware of?

We did recently noticed that the nodejs buildpack recently removed some old versions from the manifest.yml.  That made us sad but a topic for a separate issue.

**Comment by youngm** [comment]
@Dannyzen To be clear although most buildpacks only allow you to download stuff in the manifest.yml (equal to what gets put into the cached buildpack) the java-buildpack allows for the use of any version of any dependency through env modification which our users take advantage of.  I'd like to discuss with the buildpack team in another issue a way to support more then just the trimmed and cached versions of other buildpack's dependencies.

**Comment by youngm** [comment]
@Dannyzen I see that it appears there is an online java buildpack package in the release.  That was our main issue.  I'll talk to the buildpack team first about support for older versions and reopen this issue then.
