### ISSUE TITLE
config/final.yml says "file_name: stacks"

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/buildpack-releases#2]
For example: https://github.com/cloudfoundry/buildpack-releases/blob/master/binary-buildpack-release/config/final.yml#L3

I don't think `file_name` is even a relevant key in the `final.yml` files.  The key should probably be `final_name`.  And then, it shouldn't be `stacks` for all the names, in fact it shouldn't be `stacks` for any of the names.

**Comment by jtarchie** [comment]
Good catch! We'll revisit this. Was this causing any problems anywhere?

**Comment by jtarchie** [comment]
@Amit-PivotalLabs, we believe [this commit](https://github.com/cloudfoundry/buildpack-releases/commit/d500e8bd844347d0eabb90479043ac0120fa4459) resolves the issue.

Closing. Please reopen if there are any other issues related to this.
